# Site wide configuration

title: WordQuiz
locale: en_US

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Giannis Variozidis & vivipap
  bio: "WordQuiz Website."
  # Do not include the @ symbol in your Twitter username
  linkedin: Giannis-Variozidis
  github: jvario


theme: jekyll-theme-slate
